name: Hospital Engine Update

on:
  schedule:
    - cron: '*/30 * * * *' # Runs every 30 mins
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4 # Updated from v3

      - name: Setup Python
        uses: actions/setup-python@v5 # Updated from v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install pandas xgboost sqlalchemy mysql-connector-python matplotlib sklearn

      - name: Run Prediction Engine
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: python your_script_name.py # Change this to your actual filename
